### PR TITLE
Illumos does not support set_reuse_port, reuse_address is sufficient

### PR DESCRIPTION
**Pull request by urknall**
Would be great to get this as new version on crates.io
Thank you!

### CODE REVIEW

**Comment by willstott101** [comment]
Would this be better as `#[cfg(all(not(target_os = "windows"), not(target_os = "illumos")))]` actually now I've written that out it's horrible. I'll try and get a release out later today. Thanks

**Comment by urknall** [comment]
indeed i had it first the way you wrote, but i found it to confusing. do as you please ;)

thank you!

**Comment by urknall** [comment]
maybe this way its cleaner and easier to expand when the list of os not supporting this feature is growing:

        #[cfg(any(
            (not(target_os = "illumos"),
            (not(target_os = "windows")
        ))]

**Comment by urknall** [comment]
#[cfg(any(
            not(target_os = "illumos"),
            not(target_os = "windows")
        ))]

now we have it finally ;)

**Comment by willstott101** [comment]
I'm pretty sure it should be `cfg(all(`, not `cfg(any(` but that's clearly meaning it's more confusing than it needs to be. So I've merged your original commit and release as `0.6.2` - thanks!

**Pull request closed without merging**
